// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace LivrariaControleEmprestimo.DATA.Models
{
    public partial class Livro
    {
        public Livro()
        {
            LivroClienteEmprestimo = new HashSet<LivroClienteEmprestimo>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("livroNome")]
        [StringLength(50)]
        [DisplayName("Nome")]
        public string LivroNome { get; set; }
        [Required]
        [Column("livroAutor")]
        [StringLength(100)]
        [DisplayName("Autor")]
        public string LivroAutor { get; set; }
        [Required]
        [Column("livroEditora")]
        [StringLength(50)]
        [DisplayName("Editora")]
        public string LivroEditora { get; set; }
        [Column("livroAnoPublicacao", TypeName = "datetime")]
        [DisplayName("Ano de Publicação")]
        public DateTime LivroAnoPublicacao { get; set; }
        [Required]
        [Column("livroEdicao")]
        [StringLength(50)]
        [DisplayName("Edição")]
        public string LivroEdicao { get; set; }

        [InverseProperty("LceIdLivroNavigation")]
        public virtual ICollection<LivroClienteEmprestimo> LivroClienteEmprestimo { get; set; }
    }
}