// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace LivrariaControleEmprestimo.DATA.Models
{
    [Keyless]
    public partial class VwLivroClienteEmprestimo
    {
        [Required]
        [Column("cliCPF")]
        [StringLength(14)]
        [DisplayName("CPF")]
        public string CliCpf { get; set; }
        [Required]
        [Column("cliNome")]
        [StringLength(200)]
        [DisplayName("Nome do Cliente")]
        public string CliNome { get; set; }
        [Required]
        [Column("livroNome")]
        [StringLength(50)]
        [DisplayName("Nome do Livro")]
        public string LivroNome { get; set; }
        [Column("id")]
        public int Id { get; set; }
        public int LceIdLivro { get; set; }
        public int LceIdCliente { get; set; }
        [Column(TypeName = "datetime")]
        [DisplayName("Empréstimo")]
        public DateTime LceDataEmprestimo { get; set; }
        [Column(TypeName = "datetime")]
        [DisplayName("Entrega")]
        public DateTime LceDataEntrega { get; set; }
        [DisplayName("Entregue")]
        public bool LceEntregue { get; set; }
    }
}